import {
    Asset,
    Token,
    OfferType,
    OrderSide,
    ExchangeMetadata,
    APIConfig,
    BaseFetch, FeesInfo
} from "web3-accounts"
import {BigNumber, ECSignature} from 'web3-wallets'

export {
    NULL_BLOCK_HASH,
    NULL_ADDRESS, getProvider, getEstimateGas,
    ethSend,
    BigNumber,
    ETH_TOKEN_ADDRESS,
    CHAIN_CONFIG,
    getChainRpcUrl,
    hexUtils,
    getEIP712DomainHash,
    createEIP712TypedData,
    sleep
} from 'web3-wallets'
export type {Signature, WalletInfo, LimitedCallSpec, EIP712TypedData, EIP712Domain} from 'web3-wallets'


export {OrderSide, BaseFetch}
export type {Asset, Token, APIConfig, ExchangeMetadata, ECSignature, FeesInfo}

export interface OrdersQueryParams {
    token_ids?: string[]
    asset_contract_address?: string
    payment_token_address?: string
    include_bundled?: boolean
    maker?: string
    taker?: string
    side?: number
    owner?: string
    order_by?: string
    limit?: number
    offset?: number
}

export interface AssetsQueryParams {
    assets?: {
        asset_contract_addresses: string
        token_ids?: string
    }[],
    owner?: string
    limit?: number
    include_orders?: boolean
}

export interface AssetCollection extends FeesInfo {
    name: string
    symbol: string
    address?: string
    token_id?: string
    schema_name?: string
    nft_version?: string
    created_date?: string
    sell_orders?: any
}

export enum FeeMethod {
    ProtocolFee = 0,
    SplitFee = 1
}


export enum SaleKind {
    FixedPrice = 0,
    DutchAuction = 1
}

export enum HowToCall {
    Call = 0,
    DelegateCall = 1,
    StaticCall = 2,
    Create = 3
}

export interface UnhashedOrder extends BaseOrder {
    feeMethod: FeeMethod
    side: OrderSide
    saleKind: SaleKind
    howToCall: HowToCall
    quantity: BigNumber
    offerType?: OfferType

    // Element-specific
    makerReferrerFee: BigNumber
    waitingForBestCounterOrder?: boolean
    englishAuctionReservePrice?: BigNumber

    metadata: ExchangeMetadata
}

export interface UnsignedOrder extends UnhashedOrder {
    hash: string
    nonce?: string | number
}

export interface OpenSeaUser {
    // Username for this user
    username: string
}

export interface OpenSeaAccount {
    // Wallet address for this account
    address: string
    // Public configuration info, including "affiliate" for users who are in the Element affiliate program
    config: string

    // This account's profile image - by default, randomly generated by the server
    profileImgUrl: string

    // More information explicitly set by this account's owner on Element
    user: OpenSeaUser | null
}

export interface PaymentTokenToken extends Token {
    imageUrl?: string
    ethPrice?: string
    usdPrice?: string
}

/**
 * Orders don't need to be signed if they're pre-approved
 * with a transaction on the contract to approveOrder_
 */
export interface Order extends UnsignedOrder, Partial<ECSignature> {
    // Read-only server-side appends
    createdTime?: BigNumber
    currentPrice?: BigNumber
    currentBounty?: BigNumber
    makerAccount?: OpenSeaAccount
    takerAccount?: OpenSeaAccount
    feeRecipientAccount?: OpenSeaAccount
    paymentTokenContract?: PaymentTokenToken
    cancelledOrFinalized?: boolean
    markedInvalid?: boolean
    asset?: any
    assetBundle?: any
    id?: any
    orderHash?: any
}


export interface UnsignedOrder extends UnhashedOrder {
    hash: string
    nonce?: string | number
}

export interface OrderJSON extends Partial<ECSignature> {
    exchange: string
    maker: string
    taker: string
    makerRelayerFee: string
    takerRelayerFee: string
    makerProtocolFee: string
    takerProtocolFee: string
    makerReferrerFee: string
    feeRecipient: string
    feeMethod: number
    side: number
    saleKind: number
    target: string
    howToCall: number
    calldata: string
    replacementPattern: string
    staticTarget: string
    staticExtradata: string
    paymentToken: string
    quantity: string
    basePrice: string
    englishAuctionReservePrice: string | undefined
    extra: string

    // createdTime is undefined when order hasn't been posted yet
    // createdTime?: number | string
    listingTime: number | string
    expirationTime: number | string

    salt: string

    metadata: ExchangeMetadata

    hash: string
    nonce?: number | string
    orderHash?: string
    chain?: string
    chainId?: string
}

export interface BaseOrder {
    exchange: string
    maker: string
    taker: string
    makerRelayerFee: BigNumber
    takerRelayerFee: BigNumber
    makerProtocolFee: BigNumber
    takerProtocolFee: BigNumber
    feeRecipient: string
    feeMethod: number
    side: number
    saleKind: number
    target: string
    howToCall: number
    calldata: string
    replacementPattern: string
    staticTarget: string
    staticExtradata: string
    paymentToken: string
    basePrice: BigNumber
    extra: BigNumber
    listingTime: BigNumber
    expirationTime: BigNumber
    salt: BigNumber
}

